// generated by bench/browser.mjs. Do not edit.
// Real Chromium load of the built artifacts, median of 5 runs.
// transferBytes counts wire bytes; decodedBytes is the unpacked size.
export const pageLoad = [
  {"page":"docs site","requests":7,"transferBytes":448666,"decodedBytes":446566,"domContentLoadedMs":83,"loadMs":92,"heapBytes":10000000},
  {"page":"cdn demo","requests":30,"transferBytes":176029,"decodedBytes":167029,"domContentLoadedMs":43,"loadMs":44,"heapBytes":10000000}
] as const
