<script lang="ts">
  // generated by scripts/gen-logo.mjs. do not edit by hand.
  interface Props {
    size?: number
    class?: string
  }
  let { size = 20, class: className }: Props = $props()
</script>

<svg
  viewBox="0 0 64 64"
  width={size}
  height={size}
  class={className}
  role="img"
  aria-label="sigil-ui"
>
  <rect width="64" height="64" rx="16" fill="var(--sig-accent, #4f46e5)" />
  <path
    d="M 43 21 C 43 13, 21 13, 21 23 C 21 31, 43 31, 43 41 C 43 51, 21 51, 21 42"
    fill="none"
    stroke="var(--sig-accent-fg, #fff)"
    stroke-width="6"
    stroke-linecap="round"
  />
</svg>
