// Real-browser page-load benchmark. Serves a built directory over a
// throwaway HTTP server, loads it in Chromium five times, and records
// request count, transferred bytes, DOMContentLoaded and load timings,
// and post-load JS heap. Results land in results.json and
// site/src/browser.ts.
//
//   node bench/browser.mjs
//
// Requires site/dist (pnpm -F sigil-site build) and installed
// Playwright browsers. Skips gracefully when either is missing.

import { createServer } from 'node:http'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const BENCH = dirname(fileURLToPath(import.meta.url))
const REPO = join(BENCH, '..')
const RUNS = 5

const MIME = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.css': 'text/css',
  '.svg': 'image/svg+xml',
  '.json': 'application/json',
  '.txt': 'text/plain',
  '.woff2': 'font/woff2',
  '.png': 'image/png',
  '.ico': 'image/x-icon'
}

function serve(dir) {
  const server = createServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://x')
    let path = join(dir, url.pathname === '/' ? 'index.html' : url.pathname)
    if (!path.startsWith(dir) || !existsSync(path)) {
      res.writeHead(404).end('not found')
      return
    }
    res.writeHead(200, { 'content-type': MIME[extname(path)] ?? 'application/octet-stream' })
    res.end(readFileSync(path))
  })
  return new Promise((resolve) =>
    server.listen(0, '127.0.0.1', () =>
      resolve({ server, url: `http://127.0.0.1:${server.address().port}` })
    )
  )
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b)
  return sorted[Math.floor(sorted.length / 2)]
}

async function measure(page, url) {
  await page.goto(url, { waitUntil: 'load' })
  await page.waitForLoadState('networkidle')
  return page.evaluate(() => {
    const nav = performance.getEntriesByType('navigation')[0]
    const resources = performance.getEntriesByType('resource')
    const transfer =
      (nav?.transferSize ?? 0) + resources.reduce((n, r) => n + (r.transferSize ?? 0), 0)
    const decoded =
      (nav?.decodedBodySize ?? 0) + resources.reduce((n, r) => n + (r.decodedBodySize ?? 0), 0)
    return {
      requests: resources.length + 1,
      transferBytes: transfer,
      decodedBytes: decoded,
      domContentLoadedMs: Math.round(nav?.domContentLoadedEventEnd ?? 0),
      loadMs: Math.round(nav?.loadEventEnd ?? nav?.duration ?? 0),
      heapBytes: performance.memory?.usedJSHeapSize ?? null
    }
  })
}

async function bench(page, name, url) {
  const runs = []
  for (let i = 0; i < RUNS; i++) runs.push(await measure(page, url))
  return {
    page: name,
    requests: Math.round(median(runs.map((r) => r.requests))),
    transferBytes: Math.round(median(runs.map((r) => r.transferBytes))),
    decodedBytes: Math.round(median(runs.map((r) => r.decodedBytes))),
    domContentLoadedMs: Math.round(median(runs.map((r) => r.domContentLoadedMs))),
    loadMs: Math.round(median(runs.map((r) => r.loadMs))),
    heapBytes:
      runs[0]?.heapBytes == null ? null : Math.round(median(runs.map((r) => r.heapBytes ?? 0)))
  }
}

async function main() {
  let chromium
  try {
    ;({ chromium } = await import('@playwright/test'))
  } catch {
    console.log('browser bench skipped: @playwright/test not installed')
    return
  }
  const targets = [
    { name: 'docs site', dir: join(REPO, 'site', 'dist') },
    { name: 'cdn demo', dir: join(REPO, 'cdn'), file: 'demo.html' }
  ].filter((t) => existsSync(join(t.dir, t.file ?? 'index.html')))
  if (!targets.length) {
    console.log('browser bench skipped: nothing built')
    return
  }

  const browser = await chromium.launch()
  const page = await browser.newPage()
  const out = []
  for (const t of targets) {
    const { server, url } = await serve(t.dir)
    const target = t.file ? `${url}/${t.file}` : url
    try {
      out.push(await bench(page, t.name, target))
    } finally {
      server.close()
    }
  }
  await browser.close()

  const resultsPath = join(BENCH, 'results.json')
  const prior = existsSync(resultsPath) ? JSON.parse(readFileSync(resultsPath, 'utf8')) : {}
  const results = Array.isArray(prior) ? { tools: prior } : prior
  results.browser = out
  writeFileSync(resultsPath, JSON.stringify(results, null, 2) + '\n')

  const rows = out.map((r) => `  ${JSON.stringify(r)}`)
  writeFileSync(
    join(REPO, 'site', 'src', 'browser.ts'),
    `// generated by bench/browser.mjs. Do not edit.
// Real Chromium load of the built artifacts, median of ${RUNS} runs.
// transferBytes counts wire bytes; decodedBytes is the unpacked size.
export const pageLoad = [
${rows.join(',\n')}
] as const
`
  )

  for (const r of out) {
    console.log(
      `${r.page.padEnd(12)} requests=${r.requests}` +
        ` transfer=${(r.transferBytes / 1024).toFixed(0)}KB` +
        ` decoded=${(r.decodedBytes / 1024).toFixed(0)}KB` +
        ` dcl=${r.domContentLoadedMs}ms load=${r.loadMs}ms` +
        (r.heapBytes != null ? ` heap=${(r.heapBytes / 1048576).toFixed(1)}MB` : '')
    )
  }
}

await main()
