// Extracts the :global() style blocks from every component .svelte file into
// dist/components.css so the visual layer works without Svelte or any JS at
// all. Pair with theme.css for a complete zero-JS styling contract.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const SRC = new URL('../src/lib', import.meta.url).pathname
const OUT = new URL('../dist/components.css', import.meta.url).pathname

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) yield* walk(path)
    else if (entry.name.endsWith('.svelte')) yield path
  }
}

const blocks = []
for (const file of walk(SRC)) {
  const source = readFileSync(file, 'utf8')
  const styles = source.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)
  for (const match of styles) {
    const body = match[1].replaceAll(/:global\(([^)]*)\)/g, '$1')
    blocks.push(`/* ${file.slice(SRC.length + 1)} */\n${body.trim()}`)
  }
}

const css = `/* sigil-ui component styles. Generated by scripts/gen-css.mjs.
   Import after theme.css for a zero-JS styling contract:

     import 'sigil-ui/theme.css'
     import 'sigil-ui/components.css'

   or <link> both files in plain HTML. */

${blocks.join('\n\n')}
`

function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{}:;,>~])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim()
}

mkdirSync(join(OUT, '..'), { recursive: true })
writeFileSync(OUT.replace(/\.css$/, '.min.css'), minifyCss(css) + '\n')
writeFileSync(OUT, css)
console.log(`components.css: ${blocks.length} style blocks, ${css.length} bytes`)
