// Generates the sigil mark: site/public/favicon.svg and site/src/Logo.svelte.
// The glyph is an S-curve inside a rounded square, parameterized below.
// Run: node scripts/gen-logo.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'

const root = fileURLToPath(new URL('..', import.meta.url))

const SIZE = 64
const RADIUS = 16
const STROKE = 6
const ACCENT = '#4f46e5'
const ACCENT_DARK = '#6366f1'

// S-curve glyph: top-right to bottom-left, two lobes meeting at center.
const glyph = [
  'M 43 21',
  'C 43 13, 21 13, 21 23',
  'C 21 31, 43 31, 43 41',
  'C 43 51, 21 51, 21 42'
].join(' ')

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${ACCENT_DARK}"/>
      <stop offset="1" stop-color="${ACCENT}"/>
    </linearGradient>
  </defs>
  <rect width="${SIZE}" height="${SIZE}" rx="${RADIUS}" fill="url(#g)"/>
  <path d="${glyph}" fill="none" stroke="#fff" stroke-width="${STROKE}" stroke-linecap="round"/>
</svg>
`

const component = `<script lang="ts">
  // generated by scripts/gen-logo.mjs. do not edit by hand.
  interface Props {
    size?: number
    class?: string
  }
  let { size = 20, class: className }: Props = $props()
</script>

<svg
  viewBox="0 0 ${SIZE} ${SIZE}"
  width={size}
  height={size}
  class={className}
  role="img"
  aria-label="sigil-ui"
>
  <rect width="${SIZE}" height="${SIZE}" rx="${RADIUS}" fill="var(--sig-accent, ${ACCENT})" />
  <path
    d="${glyph}"
    fill="none"
    stroke="var(--sig-accent-fg, #fff)"
    stroke-width="${STROKE}"
    stroke-linecap="round"
  />
</svg>
`

writeFileSync(join(root, 'site/public/favicon.svg'), favicon)
writeFileSync(join(root, 'site/src/Logo.svelte'), component)
console.log('wrote site/public/favicon.svg and site/src/Logo.svelte')
