// Measures the shipped payload and writes site/src/sizes.ts so the docs site
// can show real numbers. Runs during the site prebuild after pnpm build.

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { gzipSync } from 'node:zlib'

const ROOT = new URL('..', import.meta.url).pathname
const DIST = join(ROOT, 'dist')
const OUT = join(ROOT, 'site', 'src', 'sizes.ts')

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) yield* walk(path)
    else yield path
  }
}

const kb = (bytes) => Math.round(bytes / 1024)

function sizeOf(files) {
  let raw = 0
  let gz = 0
  for (const f of files) {
    const text = readFileSync(f)
    raw += text.length
    gz += gzipSync(text).length
  }
  return { kb: kb(raw), gz }
}

const allJs = [...walk(DIST)].filter((f) => f.endsWith('.js'))
const headlessJs = allJs.filter((f) => f.includes(`${join(DIST, 'headless')}`))

const cssFiles = ['components.css', 'components.min.css']
  .map((n) => join(DIST, n))
  .filter((f) => statSync(f, { throwIfNoEntry: false }))
const themeFile = join(DIST, 'theme', 'sigil.css')
const engineFile = join(ROOT, 'css', 'engine.mjs')

const sizes = {
  js: sizeOf(allJs),
  headless: sizeOf(headlessJs),
  components: sizeOf(cssFiles.filter((f) => f.endsWith('components.css'))),
  componentsMin: sizeOf(cssFiles.filter((f) => f.endsWith('components.min.css'))),
  theme: sizeOf([themeFile]),
  engine: sizeOf([engineFile])
}

const body = `// generated by scripts/gen-sizes.mjs during site build. Do not edit.
export const sizes = ${JSON.stringify(sizes, null, 2)} as const
export function fmt(bytes: number) {
  return bytes < 1024 ? bytes + ' B' : (bytes / 1024).toFixed(1) + ' kB'
}
`

writeFileSync(OUT, body)
console.log(
  `sizes.ts: js ${kb(sizes.js.gz)} kB gz, components.min.css ${kb(sizes.componentsMin.gz)} kB gz`
)
